markdown: kramdown
highlighter: rouge
excerpt_separator: ""

google_analytics_id: UA-86254916-2
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

collections:
  docs:
    output: true

twitter:
  username: plumplot

logo: img/logo.png
